### ISSUE TITLE
How to use saved_model api to store the model?

### ISSUE THREAD

**Issue by StephenLee2016** [brianhuang1019/RL-Chatbot#1]
Hi, i wander to know if you have tried save the chatbot with saved_model api?Do you have any ideas?
你好，我想知道你有尝试过用saved_model来保存模型吗？我想在tensorflow serving上加载chatbot模型，但是只能加载saved_model保存的模型文件。

**Comment by brianhuang1019** [comment]
tf.saved_model 我沒用過，不好意思。

我比較常用的是 tf.save.saver()
當你想保存一個 tensorflow 的 session 時
只需要一行：
saver.save(<your_session>, <saved_model_name>)
