### ISSUE TITLE
how to generate the candidate action list given an input source[p,q] 

### ISSUE THREAD

**Issue by Amber819** [brianhuang1019/RL-Chatbot#5]
Thanks for the code.
In the paper, there is a description "Given an input source [pi; qi], we generate a candidate list A." how to generate the candidate action list in your code? I could not find the code for this.

**Comment by brianhuang1019** [comment]
Yeah, you are right.
I didn't generate the action list, I generate only one action instead.
And I do policy gradient according to the reward function with the generated action.
