### ISSUE TITLE
您好，我重新训练SEQ2SEQ模型后用 text.py 但是得到以下结果:

### ISSUE THREAD

**Issue by chaiyixuan** [brianhuang1019/RL-Chatbot#6]
您好，我重新训练SEQ2SEQ模型后用 text.py 但是得到以下结果:
Concentration concentration concentration concentration planning priest.
Concentration concentration concentration concentration planning concentration planning priest.
Concentration concentration concentration concentration planning priest.
Concentration concentration concentration concentration planning concentration planning priest.
Concentration concentration concentration concentration planning priest.
Concentration concentration concentration concentration planning concentration planning priest.
您知道是什么原因么？

**Comment by brianhuang1019** [comment]
很抱歉，
我自己執行時沒有這個錯誤
不知道您在執行時版本是否正確呢？

**Comment by brianhuang1019** [comment]
可以試試看 RMSprop
GradientDecent 收斂太慢。
